# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Covid Data' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire',      '5.4.3'

  target 'Covid DataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Covid DataUITests' do
    # Pods for testing
  end

end
